baseURL = ''
languageCode = 'en-us'
title = 'Matt Mastin'
theme = ["hugo-embed-pdf-shortcode", "ananke"]
author = "Matt Mastin"
favicon = "static/favicon.ico"

enableInlineShortcodes = true

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/mathmastin"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/matt-mastin-66667b17/"

[[params.ananke_socials]]
name = "github"
url = "https://www.github.com/mattmastin"
label = "mattmastin"

[params]
  recent_posts_number = 0