baseURL = 'http://mattmastin.com/'
languageCode = 'en-us'
title = 'Matt Mastin'
theme = "ananke"
author = "Matt Mastin"
favicon = "static/favicon.ico"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/mathmastin"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/matt-mastin-66667b17/"